### ISSUE TITLE
Use hash router to support domain use 

### ISSUE THREAD

**Issue by samepant** [gnosis/zodiac-modifier-roles#107]
Right now, deep linking into the app is not possible as navigating to `https://roles.dev.gnosisguild.org/rin:0xE4E5237B3BE947FB99C491238cFEE3E5f190451F/roles/new` results in an ipfs gateway error:
```
ipfs resolve -r /ipns/roles.dev.gnosisguild.org/rin:0xE4E5237B3BE947FB99C491238cFEE3E5f190451F/roles/new: no link named "rin:0xE4E5237B3BE947FB99C491238cFEE3E5f190451F" under QmaChLj3n2Nv7jcVUQw7uq24zFufqtMRqUT9FxuWYVtHmF
```
Using the HashRouter from react-router will solve this

**Comment by manboy-eth** [comment]
This turns out to be more complicated than expected because when we use the HashRouter instead of the BrowserRouter, the routes do not work as expected when it is opened as a Gnosis Safe app.

Everything behind the `#` is ignored in the Gnosis Safe app (while it works as expected when opening the app directly) 🤔 

Investigating...

**Comment by manboy-eth** [comment]
@juliopavila Fixed in the commit mentioned above.

Some samples of how to use it:
- Via Gnosis Safe: `https://gnosis-safe.io/app/rin:0x5a30016bE71705326F8f1Fd0306D3Fbe5d215365/apps?appUrl=http://localhost:3000/%23/eth:0xE4E5237B3BE947FB99C491238cFEE3E5f190451F` - we use `%23` URL-encode for `#`

- Direct link: `http://localhost:3000/#/eth:0xE4E5237B3BE947FB99C491238cFEE3E5f190451F`
